/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import board.Board;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import inicio.Menu;

/**
 *
 * @author Ruben Chevez G
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        USUARIO1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passtxt = new javax.swing.JTextField();
        Ingresartxt = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        USUARIO1.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        USUARIO1.setText("REGRESAR");
        USUARIO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USUARIO1MouseClicked(evt);
            }
        });
        jPanel1.add(USUARIO1);
        USUARIO1.setBounds(920, 500, 240, 60);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USUARIO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(840, 310, 230, 40);

        usertxt.setBackground(new java.awt.Color(227, 197, 151));
        usertxt.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        usertxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(usertxt);
        usertxt.setBounds(820, 350, 270, 30);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONTRASEÑA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(810, 400, 290, 40);

        passtxt.setBackground(new java.awt.Color(227, 197, 151));
        passtxt.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        passtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(passtxt);
        passtxt.setBounds(820, 440, 280, 30);

        Ingresartxt.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        Ingresartxt.setText("INGRESAR");
        Ingresartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresartxtMouseClicked(evt);
            }
        });
        jPanel1.add(Ingresartxt);
        Ingresartxt.setBounds(660, 510, 230, 40);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/inicio.png"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1280, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USUARIO1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USUARIO1MouseClicked
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_USUARIO1MouseClicked

    private void IngresartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresartxtMouseClicked
            Board b = new Board();
            b.setVisible(true);
            
            this.dispose();
    }//GEN-LAST:event_IngresartxtMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ingresartxt;
    private javax.swing.JLabel USUARIO1;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
