/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import createplayer.CreatePlayer;
import javax.swing.ImageIcon;
import login.Login;

/**
 *
 * @author Ruben Chevez G
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        playtxt = new javax.swing.JLabel();
        exittxt = new javax.swing.JLabel();
        createtxt = new javax.swing.JLabel();
        USUARIO2 = new javax.swing.JLabel();
        USUARIO4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel3.setText("EXIT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 330, 130, 40);

        playtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playtxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio/simbol1.png"))); // NOI18N
        playtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playtxtMouseExited(evt);
            }
        });
        jPanel1.add(playtxt);
        playtxt.setBounds(230, 160, 120, 210);

        exittxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exittxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio/simbol2.png"))); // NOI18N
        exittxt.setToolTipText("");
        exittxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exittxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exittxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exittxtMouseExited(evt);
            }
        });
        jPanel1.add(exittxt);
        exittxt.setBounds(440, 140, 170, 230);

        createtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createtxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio/simbol3.png"))); // NOI18N
        createtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createtxtMouseExited(evt);
            }
        });
        jPanel1.add(createtxt);
        createtxt.setBounds(340, 320, 120, 130);

        USUARIO2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        USUARIO2.setText("CREATE NEW PLAYER");
        jPanel1.add(USUARIO2);
        USUARIO2.setBounds(170, 440, 460, 50);

        USUARIO4.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        USUARIO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USUARIO4.setText("LOGIN");
        jPanel1.add(USUARIO4);
        USUARIO4.setBounds(190, 300, 190, 80);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio/menu2.png"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1280, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playtxtMouseEntered
        playtxt.setIcon( new ImageIcon( Class.class.getResource("/inicio/simbol1_1.png") ) );
    }//GEN-LAST:event_playtxtMouseEntered

    private void playtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playtxtMouseExited
        playtxt.setIcon( new ImageIcon( Class.class.getResource("/inicio/simbol1.png") ) );
    }//GEN-LAST:event_playtxtMouseExited

    private void exittxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseEntered
        exittxt.setIcon( new ImageIcon( Class.class.getResource("/inicio/simbol2_1.png") ) );
    }//GEN-LAST:event_exittxtMouseEntered

    private void exittxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseExited
        exittxt.setIcon( new ImageIcon( Class.class.getResource("/inicio/simbol2.png") ) );
    }//GEN-LAST:event_exittxtMouseExited

    private void createtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createtxtMouseEntered
        createtxt.setIcon( new ImageIcon( Class.class.getResource("/inicio/simbol3_1.png") ) );
    }//GEN-LAST:event_createtxtMouseEntered

    private void createtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createtxtMouseExited
        createtxt.setIcon( new ImageIcon( Class.class.getResource("/inicio/simbol3.png") ) );
    }//GEN-LAST:event_createtxtMouseExited

    private void exittxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseClicked
          System.exit(0);
    }//GEN-LAST:event_exittxtMouseClicked

    private void createtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createtxtMouseClicked
            CreatePlayer p = new CreatePlayer();
            p.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_createtxtMouseClicked

    private void playtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playtxtMouseClicked
        Login l = new Login();
            l.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_playtxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel USUARIO2;
    private javax.swing.JLabel USUARIO4;
    private javax.swing.JLabel createtxt;
    private javax.swing.JLabel exittxt;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playtxt;
    // End of variables declaration//GEN-END:variables
}
